sudo: false

language: php

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
    - php: nightly
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer install

script: ./bin/phpunit
