#!/usr/bin/env php
<?php

use React\ChildProcess\Process;
use React\EventLoop\Factory as EventFactory;
use Symfony\Component\Yaml\Yaml;

require 'vendor/autoload.php';

$start_time = microtime(true);

$config = Yaml::parse(file_get_contents('config.yml'));

if (null === $config) {
    exit('Config file does not exists');
}

foreach($config['ace']['command-chunks'] as $chunkName => $commandChunk) {
    $loop = EventFactory::create();
    echo PHP_EOL . 'Starting chunk ' . $chunkName . PHP_EOL;
    echo '----------------------------------------------' . PHP_EOL;

    foreach($commandChunk as $command) {
        $process = new Process($command);
        $process->start($loop);

        echo "\tStarting " . $command . '...' . ' PID: ' . $process->getPid() . PHP_EOL;

        $process->stderr->on('data', function($outputChunk) use($command) {
            echo "\t\t ERROR RUNNING COMMAND '$command': " . $outputChunk . PHP_EOL;
        });

        $process->on('exit', function() use($command) {
            echo "\t" . $command . ' finished!' . PHP_EOL;
        });
    }

    $loop->run();
}

$end_time = microtime(true);

echo PHP_EOL . 'Time spent: ' . round($end_time - $start_time, 2) . ' seconds' . PHP_EOL . PHP_EOL;
