#!/usr/bin/env php
<?php

use DalaiLomo\ACE\Command\ExecuteCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$console = new Application();

$console->add(new ExecuteCommand());

$console->run();
